#ifndef MINTREMOTE_PROTOCOL_H
#define MINTREMOTE_PROTOCOL_H

#define MR_PROTOCOL_VERSION 1
#define MR_DEFAULT_PORT 5909
#define MR_TILE_WIDTH 32
#define MR_TILE_HEIGHT 16

#define MR_PIXEL_PLANAR_INDEXED 1

#define MR_MSG_PALETTE 1
#define MR_MSG_TILE 2
#define MR_MSG_FRAME_END 3
#define MR_MSG_GOODBYE 4

#define MR_HANDSHAKE_BYTES 20
#define MR_MESSAGE_HEADER_BYTES 4
#define MR_TILE_HEADER_BYTES 16

#endif

